config/routes.rb
Rails.application.routes.draw do
  root to: 'homepage#index'

  resources :users, only: [:new, :create]

  resources :transactions, only: [:index, :create] do
    collection do
      get :withdraw
      get :pay
    end
  end
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  monetize :amount_cents

  belongs_to :user

  def self.previous_in_period(user, transaction_id)
    user.transactions
      .where("created_at >= ?", user.period_start )
      .where(transaction_type: ['withdraw', 'pay'])
      .where("id < ?", transaction_id)
      .last
  end

  def self.last_non_interest_transaction_in_period(user)
    user.transactions
      .where("created_at >= ?", user.period_start )
      .where(transaction_type: ['withdraw', 'pay'])
      .max_by(&:created_at)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  include InterestHelper

  monetize :credit_limit_cents
  monetize :balance_cents

  has_many :transactions

  before_create :set_up_user

  def set_up_user
    self.credit_limit = Money.new(100000)
    self.balance = Money.new(0)
    self.period_start = Time.zone.now.beginning_of_day
  end

  # Balance starts at 0 and goes negative when you borrow money.
  # When updating the balance you should pass in a negative amount
  # for a withdrawal.
  def update_balance(amount)
    self.credit_limit += amount
    self.balance += amount
    self.save
  end

  def close_period
    calculate_interest(self)

    # interest_for_period is made negative because it is money owed.
    total_interest = -interest_for_period
    Transaction.create(amount: total_interest, transaction_type: 'period interest', user_id: self.id)

    update_balance(total_interest)
    reset_period_start
  end

  def interest_for_period
    interest_transactions = transactions
                            .where("created_at >= ?", self.period_start )
                            .where(transaction_type: ['interest'])

    interest = Money.new(0)
    interest_transactions.each do |transaction|
      interest += transaction.amount
    end

    return interest
  end

  def reset_period_start
    self.period_start = Time.zone.now.beginning_of_day
    self.save
  end

  def valid_transaction?(amount)
    if self.balance + amount > Money.new(0)
      return false
    end

    if self.credit_limit + amount < Money.new(0)
      return false
    end

    return true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  before_action :require_login, except: [:index]

  def index
    if signed_in?
      render :index
    else
      render :welcome
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include InterestHelper

  before_action :require_login

  def index
    @transactions = current_user
                      .transactions
                      .where(transaction_type: ['withdraw', 'pay', 'period interest'])
  end

  # POST /transactions
  def create

    @transaction = Transaction.new(transaction_params)
    if @transaction.transaction_type == 'withdraw'
      @transaction.amount = @transaction.amount.amount * BigDecimal.new('-1')
    end
    @transaction.user_id = current_user.id

    respond_to do |format|
      if (@transaction.amount != Money.new(0)) && current_user.valid_transaction?(@transaction.amount)
        if @transaction.save

          calculate_interest(current_user, @transaction)

          current_user.update_balance(@transaction.amount)
          format.html { redirect_to transactions_path, notice: 'Transaction was successfully completed.' }
        end
      else
        format.html { redirect_to :back, flash: {error: 'Invalid Transaction'} }
      end
    end
  end

  def withdraw
    @transaction = Transaction.new(transaction_type: 'withdraw')
  end

  def pay
    @transaction = Transaction.new(transaction_type: 'pay')
  end

  private
    def transaction_params
      params.require(:transaction).permit(:amount, :transaction_type)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :encrypted_password, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert-info"
      when "success" then "alert-success"
      when "error" then "alert-danger"
      when "alert" then "alert-warning"
    end
  end
end

app/helpers/interest_helper.rb
module InterestHelper

  def calculate_interest(user, transaction=nil)
    balance = user.balance.amount * BigDecimal.new('-1')

    return if balance == Money.new(0)

    apr = BigDecimal.new('0.35')
    days_in_year = BigDecimal.new('365')
    days_in_period = BigDecimal.new(days_since_last_transaction(user, transaction))

    interest = balance * apr / days_in_year * days_in_period

    if interest > BigDecimal.new('0')
      Transaction.create(amount: interest, transaction_type: 'interest', user_id: user.id)
    end
  end

  def days_since_last_transaction(user, transaction)
    if transaction
      last_transaction = Transaction.previous_in_period(user, transaction.id)
    else
      last_transaction = Transaction.last_non_interest_transaction_in_period(user)
    end

    if last_transaction.present?
      (Time.zone.now.to_date - last_transaction.created_at.to_date).to_i
    else
      (Time.zone.now.to_date - user.period_start.to_date).to_i
    end
  end
end

app/views/homepage/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">Account Summary</div>
      <table class="table">
        <thead>
          <tr>
            <th>Credit Limit</th>
            <th>Balance</th>
            <th>APR</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= humanized_money_with_symbol(current_user.credit_limit) %></td>
            <td><%= humanized_money_with_symbol(-current_user.balance) %></td>
            <td>35%</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-1 col-md-offset-6">
    <%= link_to 'Withdraw', withdraw_transactions_path, class: 'btn btn-default' %>
  </div>
  <div class="col-md-1">
    <%= link_to 'Pay', pay_transactions_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/homepage/welcome.html.erb
<h1>Welcome to Line of Credit</h1>
<p>
  Please <%= link_to 'sign in', sign_in_path %>
</p>
<p>
  If you have not signed up yet and you would like a line of credit, please <%= link_to 'sign up', sign_up_path %>.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LineOfCredit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Line of Credit', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Transactions', transactions_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><%= link_to 'Sign out', sign_out_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign in', sign_in_path %></li>
            <li><%= link_to 'Sign up', sign_up_path %></li>
          <% end %>
        </ul>

        <% if signed_in? %>
          <p class="navbar-text navbar-right">Welcome <%= current_user.email %></p>
        <% end %>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert <%= flash_class(key) %> alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <% @transaction.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
        Error: <%= message %>
      </div>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-2">
      <div class="form-group">
        <%= f.label :amount %>
        <%= f.text_field :amount, class: "form-control" %>
      </div>
      <%= f.hidden_field :transaction_type %>
      <%= f.submit nil, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/transactions/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">Account Summary</div>
      <table class="table">
        <tbody>
          <tr>
            <td>Balance</td>
            <td><%= humanized_money_with_symbol(-current_user.balance) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">Transactions</div>
      <table class="table">
        <thead>
          <tr>
            <th>Amount</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          <% @transactions.each do |transaction| %>
            <tr>
              <td><%= humanized_money_with_symbol(transaction.amount) %></td>
              <td><%= transaction.transaction_type %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/transactions/pay.html.erb
<h2>How much would you like to pay?</h2>

<%= render partial: 'transactions/form' %>

app/views/transactions/withdraw.html.erb
<h2>How much would you like to withdraw?</h2>

<%= render partial: 'transactions/form' %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |message| %>
      <div class="alert alert-danger" role="alert">
        Error: <%= message %>
      </div>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="password_field form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control" %>
      </div>
      <%= f.submit nil, class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render partial: 'users/form' %>

<%= link_to 'Back', root_path %>